name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
          nuget-version: 5.x
    - name: Setup .NET core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Restore dependencies nuget
      run: nuget restore ./src/GainsProject.sln
    - name: Build
      run: dotnet build --no-restore ./src/GainsProject.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/GainsProject.sln
